version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./backend:/var/www/html/backend
      - ./public:/var/www/html/public
      - ./backend/.env:/var/www/html/backend/.env
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance_app
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "3307:3306"

volumes:
  db_data: