version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    ports:
      - "8080:80"

networks:
  app-network:
volumes:
  db_data:
